version: '3.8'

services:

  search-redis:
    image: redis:7.2
    container_name: search_redis
    restart: always
    ports:
      - "6380:6379"  # Host:Container
    networks:
      - connection

  search-service:
    build: .
    container_name: search_service
    ports:
      - "8085:8085"
    depends_on:
      - search-redis
    environment:
      SPRING_REDIS_HOST: search-redis
      SPRING_REDIS_PORT: 6380  # Redis port inside container
      SPRING_WORKER_SERVICE_URL: http://worker-service:8082
    networks:
      - connection

networks:
  connection:
    external: true
    name: connection
