version: '3.8'

services:
  search-db:
    image: postgres:15
    container_name: search_postgres
    restart: always
    environment:
      POSTGRES_DB: search_db
      POSTGRES_USER: search_user
      POSTGRES_PASSWORD: search_pass
    ports:
      - "5433:5432"
    volumes:
      - search_pgdata:/var/lib/postgresql/data

  search-service:
    build: .
    container_name: search_service
    depends_on:
      - search-db
    ports:
      - "8085:8085"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://search-db:5432/search_db
      SPRING_DATASOURCE_USERNAME: search_user
      SPRING_DATASOURCE_PASSWORD: search_pass
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
    networks:
      - connection

  redis:
    image: redis:latest
    container_name: search-redis
    ports:
      - "6380:6379"


volumes:
  search_pgdata:

networks:
  connection:
    external: true
    name: connection
