version: '3.9'

services:
  api-gateway:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-gateway
    ports:
      - "8761:8761"
    networks:
      - connection
#    depends_on:
#      - user-service
#      - worker-service
#      - review-service

networks:
  connection:
    external: true
