spring:
  main:
    web-application-type: reactive
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: userService
          uri: http://user-service:8081
          predicates:
            - Path=/users/**
        - id: userAuthService
          uri: http://user-service:8081
          predicates:
            - Path=/api/user/auth/**
        - id: workerService
          uri: http://worker-service:8082
          predicates:
            - Path=/workers/**
        - id: workerAuthService
          uri: http://worker-service:8082
          predicates:
            - Path=/api/worker/auth/**
        - id: bookingService
          uri: http://booking-service:8083
          predicates:
            - Path=/bookings/**
        - id: reviewService
          uri: http://review-service:8084
          predicates:
            - Path=/reviews/**
        - id: searchService
          uri: http://search-service:8085
          predicates:
            - Path=/search/**
server:
  port: 8761


spring.session.store-type: redis
spring.data.redis.host: redis
spring.data.redis.port: 6379
spring.session.redis.namespace: app_sessions
