apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  namespace: microservices
type: Opaque
data:
  MONGO_INITDB_ROOT_USERNAME: cm9vdA==     # "root"
  MONGO_INITDB_ROOT_PASSWORD: ZXhhbXBsZQ== # "example"
  WORKER_DB_URI: bW9uZ29kYjovL3Jvb3Q6ZXhhbXBsZUBtb25nby0wLm1vbmdvOjI3MDE3L3dvcmtlcmRiP2F1dGhTb3VyY2U9YWRtaW4=
  REVIEW_DB_URI: bW9uZ29kYjovL3Jvb3Q6ZXhhbXBsZUBtb25nby0wLm1vbmdvOjI3MDE3L3Jldmlld2RiP2F1dGhTb3VyY2U9YWRtaW4=