version: '3.8'

services:
  worker-service:
    build: .
    container_name: worker-service
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SERVER_PORT=8082
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6380
      - SPRING_DATA_MONGODB_URI=mongodb://root:example@mongo:27017/workerdb?authSource=admin
    depends_on:
      - redis
      - mongo
    networks:
      - connection
    restart: always

  redis:
    image: redis:7.2
    container_name: redis_1
    ports:
      - "6380:6380"
    restart: always
    networks:
      - connection

  mongo:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - connection

networks:
  connection:
    external: true
    name: connection
