version: '3.8'

services:
  booking-db:
    image: postgres:15
    container_name: booking_postgres
    restart: always
    environment:
      POSTGRES_DB: booking_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - booking_pgdata:/var/lib/postgresql/data


  booking-service:
    build: .
    container_name: booking_service
    depends_on:
      - booking-db
    ports:
      - "8083:8083"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://booking-db:5432/booking_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres


volumes:
  booking_pgdata:

networks:
  default:
    external: true
    name: connection
