version: '3.8'

services:
  booking-db:
    image: postgres:15
    container_name: booking_postgres
    restart: always
    environment:
      POSTGRES_DB: booking_db
      POSTGRES_USER: booking_user
      POSTGRES_PASSWORD: booking_pass

    ports:
      - "5432:5432"
    volumes:
      - booking_pgdata:/var/lib/postgresql/data


  booking-service:
    build: .
    container_name: booking_service
    depends_on:
      - booking-db
    ports:
      - "8083:8083"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://booking-db:5432/booking_db
      SPRING_DATASOURCE_USERNAME: booking_user
      SPRING_DATASOURCE_PASSWORD: booking_pass
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest


volumes:
  booking_pgdata:

networks:
  default:
    external: true
    name: connection
