apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM=
  POSTGRES_PASSWORD: cG9zdGdyZXM=
  USER_DB: amRiYzpwb3N0Z3Jlc3FsOi8vcG9zdGdyZXM6NTQzMi91c2Vycw==   # base64 for "customer_db"
  BOOKING_DB: amRiYzpwb3N0Z3Jlc3FsOi8vYm9va2luZy1kYjo1NDMyL2Jvb2tpbmdfZGI=