apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM=       # base64 for "postgres"
  POSTGRES_PASSWORD: cG9zdGdyZXM=  # base64 for "1234"
  USER_DB: dXNlcnM=   # base64 for "customer_db"
  BOOKING_DB: Ym9va2luZ19kYg==